### ISSUE TITLE
Uninstall script?

### ISSUE THREAD

**Issue by ApricotFarm** [mapi68/raspi-info#2]
This is a beautiful project. But how can I uninstall it? Every installation like this should provide a means for removing itself without a trace.

**Comment by mapi68** [comment]
Hello, no need uninstall script, simply run:
`sudo apt --purge remove raspi-info -y`

If you want to remove with installed dependencies:
`sudo apt --purge autoremove raspi-info -y`

**Comment by ApricotFarm** [comment]
Awesome, thanks so much! This information should probably be included in the main README section.

Tremendous work on this, thanks again for your efforts.

**Comment by mapi68** [comment]
Done!
Regards.
