### ISSUE TITLE
SSID with Space

### ISSUE THREAD

**Issue by Jens869** [mapi68/raspi-info#3]
if the SSID contains a space, only the part up to the space is displayed.

I don't like the bitcoin in command

**Comment by mapi68** [comment]
> if the SSID contains a space, only the part up to the space is displayed.
Can you explain better?

**Comment by Jens869** [comment]
Internal IP: wlan0 192.168.178.104/23 ESSID:"Schroeders
Bit Rate=433.3 Mb/s   Tx-Power=31 dBm   
Link Quality=53/70  Signal level=-57 dBm  


ESSID:"Schroeders
SSID  "Schroeders WLAN"

**Comment by Jens869** [comment]
This work

# WLAN quality
if [[ $INTERFACE =~ wlan0 ]]; then
        echo
        echo -e -n '\e[33m'" "
        iwgetid  
        iwconfig wlan0 | grep -i "Bit Rate" | sed -e 's/^\s*//' -e '/^$/d' # REMOVE TAB
        iwconfig wlan0 | grep -i "Link Quality" | sed -e 's/^\s*//' -e '/^$/d' # REMOVE TAB
else
        echo
fi

**Comment by mapi68** [comment]
Can you open a pull request?
